In [ ]:
print("Hello World!")

Hello World!


In [ ]:
import ipywidgets as widgets

b = widgets.Button(description="Hello World", value="",disabled=False)
t = widgets.Text(value="")
output = widgets.Output()
def getText():
  with output:
    print(t.value)

b.on_click(getText(), remove=True)

In [ ]:
display(b)
display(t)

In [ ]:
b.keys

['_dom_classes',
 '_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'button_style',
 'description',
 'disabled',
 'icon',
 'layout',
 'style',
 'tooltip']

In [ ]:
t.keys

['_dom_classes',
 '_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'continuous_update',
 'description',
 'description_tooltip',
 'disabled',
 'layout',
 'placeholder',
 'style',
 'value']

In [ ]:
from IPython.display import display
button = widgets.Button(description="Click Me!")
output = widgets.Output()

display(button, output)

def on_button_clicked(b):
    with output:
        print("Button clicked.")

button.on_click(on_button_clicked)

Button(description='Click Me!', style=ButtonStyle())

Output()

In [ ]:
import requests, json
b = widgets.Button(description="Go!", value="",disabled=False) 
#b2 = widgets.Button(description ="2nd Button")
t = widgets.Text(value="", placeholder="Type a City,State(abbrev.)") 
output = widgets.Output() 
display(t,b,output)
bioset = ''
APIkey = 'd88fb36e333086aa331f6e9d819b1f71'
location = 'Nashville,TN'
response = ''
parseWeather = json.loads(getWeather.content)

def doBoth(self):
  global location,APIkey
  
  location = t.value
  query = requests.get(f'https://api.openweathermap.org/data/2.5/weather?q={location},uk&APPID={APIkey}')
  with output:
    print("hello world?")
    print(query.content)
    response = json.loads(query.content)
    return response
b.on_click(doBoth, remove=False)



Text(value='', placeholder='Type a City,State(abbrev.)')

Button(description='Go!', style=ButtonStyle())

Output()

# New Section

In [ ]:
response

''

In [ ]:
print(t.value)

Nashville,TN


In [ ]:
getDropDowns

<function __main__.getDropDowns>

In [ ]:
print(widgets.Widget.widget_types)

In [ ]:
dropList = widgets.Dropdown(
    options= ['1','2','3'],
    value='2',
    description='Number:',
    disabled=False)
output =widgets.Output()
display(dropList, output)
with output:
  print(dropList.value)

Dropdown(description='Number:', index=1, options=('1', '2', '3'), value='2')

Output()

In [ ]:
widgets.Combobox(
    # value='John',
    placeholder='Choose Someone',
    options= options,
    description='Combobox:',
    ensure_option=True,
    disabled=False
)

TraitError: ignored

In [ ]:
response



```
# This is formatted as code
```

## Numpy on Free Code Camp

In [1]:
import numpy as np

In [14]:
a = np.array([1,2,3], dtype="int32")
a

array([1, 2, 3], dtype=int32)

In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [5]:
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [6]:
b.ndim

2

In [7]:
a.ndim

1

In [8]:
b.shape

(2, 3)

In [12]:
#Get type
a.dtype

dtype('int16')

In [19]:
print(a.itemsize)
print(a.size)
print(a.nbytes)

4
3
12


In [21]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a, a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] (2, 7)


In [22]:
a[1,5]

13

In [23]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [26]:
#Getting a  little more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [27]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
a[:, 2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [33]:
# All 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [35]:
# All 1s matrix
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [37]:
np.full((2,2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [40]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [45]:
# random decimal numbers
np.random.rand(4,2,3)

array([[[0.37002019, 0.15397263, 0.359247  ],
        [0.39920892, 0.64280236, 0.79223311]],

       [[0.88966837, 0.43642405, 0.64392675],
        [0.5698668 , 0.75746724, 0.10790034]],

       [[0.67711327, 0.07792123, 0.27340991],
        [0.4807197 , 0.07767572, 0.14839591]],

       [[0.73376901, 0.11311909, 0.22915568],
        [0.45863805, 0.72678344, 0.00551864]]])

In [46]:
np.random.randint(7,size=(3,3))

array([[5, 5, 0],
       [4, 5, 6],
       [4, 6, 2]])

In [47]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
output = np.ones((5,5))

In [51]:
output
z = np.zeros((3,3))

In [52]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
z[1,1] = 9

In [54]:
output[1:4,1:4] = z

In [55]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
a = np.array([1,2,3,4,5])

In [64]:
b = a.copy()

In [65]:
b[2] = 20

In [66]:
a

array([1, 2, 3, 4, 5])

In [67]:
b

array([ 1,  2, 20,  4,  5])

In [68]:
a = np.array(([1,2,3,4,5], [6,7,8,9,10]))

In [70]:
b = np.max(a, axis=1).sum()

In [72]:
a + 2

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [73]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [74]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])

In [75]:
import matplotlib as plt

TypeError: ignored